"""A named instance of something isomorph does not generate.

A phase-locked loop, a vendor FIFO, a hard memory controller, a
third-party netlist. The design instantiates it by name with a port
map, so the place-and-route hierarchy is the hierarchy that was
written, and the real thing is handed to the fitter separately.

    altpll = blackbox('altpll',
        inputs = {'inclk0': 1, 'areset': 1},
        outputs = {'c0': 1, 'c1': 1, 'locked': 1},
        params = {'clk0_divide_by': 1, 'clk0_multiply_by': 2},
        source = 'Quartus megafunction, generated by the IP catalogue')

    inst_pll = altpll (
        inclk0 = i_clock,
        areset = areset,

        c0 = clock_sys,
        c1 = open_port(),
        locked = o_locked
    )

Directions are declared rather than inferred, because there is no
body to infer them from. Every declared port is connected, an output
the design does not want with open_port(), and an input may not be
left open, which is the rule ordinary instances follow (SPEC 3.8).

No model of it goes in the @block tree. A Python stand-in for a
memory would mean the simulated hierarchy and the fitted hierarchy
are different trees, which is the failure this project exists to
refuse, so the three built-in simulators decline to run a design
containing a blackbox and say which one stopped them. Simulating it
is a Verilator harness that links the vendor's own model, the shape
verify/run_sdram.sh already has.
"""
import sys

from .signal import Signal, OpenPort, IsomorphError, note_made


class BlackboxType:
    """What blackbox() returns: call it to make one instance."""

    def __init__ (self, module, inputs, outputs, params, source,
                  inouts = None):
        if inouts:
            raise IsomorphError(
                f'blackbox {module}: ' + ', '.join(sorted(inouts))
                + ' is bidirectional, and isomorph has no bidirectional '
                'port yet. Split it into the three wires the fitter uses '
                'anyway, an output, an output enable and an input, and '
                'connect those; the tristate itself then lives wherever '
                'your flow puts it. Efinity requires exactly that split '
                'at the top level and generates the buffer in the '
                'Interface Designer, which is why isomorph.ifaces spells '
                'a memory bus dq_o, dq_oe, dq_i. Quartus, Vivado and '
                'Lattice all take an inout at the top instead, and a '
                'bidirectional port that emits the right shape for each '
                'is ROADMAP item 14.')
        self.module = module
        self.inputs = dict(inputs or {})
        self.outputs = dict(outputs or {})
        self.params = dict(params or {})
        self.source = source
        both = set(self.inputs) & set(self.outputs)
        if both:
            raise IsomorphError(
                f'blackbox {module}: ' + ', '.join(sorted(both))
                + ' is declared an input and an output. A port that is '
                'read and driven wants two ports (SPEC 4.1).')
        if not self.inputs and not self.outputs:
            raise IsomorphError(
                f'blackbox {module}: no ports. Declare them with '
                'inputs = {...} and outputs = {...}, name to width, '
                'because there is no body to infer a direction from.')
        for name, width in list(self.inputs.items()) + \
                list(self.outputs.items()):
            if not isinstance(width, int) or isinstance(width, bool) \
                    or width < 1:
                raise IsomorphError(
                    f'blackbox {module}: port {name} has width '
                    f'{width!r}; a width is a positive int.')

    def __call__ (self, **actuals):
        return Blackbox(self, actuals)


class Blackbox:
    """One instance of a blackbox, held by the block that made it.

    Duck-types the parts of Elaborated that the hierarchy walk, the
    analyser and the parent's port map read, and nothing else: it has
    no body, so there is nothing else to have.
    """

    def __init__ (self, kind, actuals):
        self.kind = kind
        self.block_name = kind.module
        self.instance_name = None
        self.instances = {}
        self.parameters = dict(kind.params)
        self.constants = {}
        self.open_ports = set()
        self.array_name = None
        self.array_index = 0
        self.array_count = 0
        self._name_override = None
        # the line the block instantiated it on, for ordering and for
        # the comment written above it
        frame = sys._getframe(1)
        while frame is not None and frame.f_code.co_filename == __file__:
            frame = frame.f_back
        self.line = frame.f_lineno if frame is not None else 0
        self.ports = {}
        self.port_names = {}
        declared = dict(kind.inputs)
        declared.update(kind.outputs)
        unknown = set(actuals) - set(declared)
        if unknown:
            raise IsomorphError(
                f'blackbox {kind.module}: ' + ', '.join(sorted(unknown))
                + ' is not a port of it. It has '
                + ', '.join(sorted(declared)) + '.')
        missing = set(declared) - set(actuals)
        if missing:
            raise IsomorphError(
                f'blackbox {kind.module}: ' + ', '.join(sorted(missing))
                + ' is not connected. Every port of a blackbox is '
                'connected by name, an output you do not want with '
                'open_port(), because nothing here can see what it does '
                'with the ones you leave out.')
        for name, value in actuals.items():
            if isinstance(value, OpenPort):
                if name in kind.inputs:
                    raise IsomorphError(
                        f'blackbox {kind.module}: input {name} is '
                        'open_port(). An input drives something inside '
                        'the part and may not be left open.')
                self.open_ports.add(name)
                value = Signal(declared[name])
            if not isinstance(value, Signal):
                raise IsomorphError(
                    f'blackbox {kind.module}: port {name} is connected '
                    f'to {value!r}, which is not a signal.')
            if value.width != declared[name]:
                raise IsomorphError(
                    f'blackbox {kind.module}: port {name} is '
                    f'{declared[name]} bits and is connected to '
                    f'{value.width}. A blackbox port map does not resize.')
            self.ports[name] = value
        note_made(self)

    @property
    def module_name (self):
        return self.kind.module

    @property
    def shape (self):
        """Every instance of one blackbox is the same stub. The
        vendor's part has one port list and isomorph never sees
        inside it, so there is nothing that could make two."""
        return (self.kind.module, (), ())

    @property
    def _built_name (self):
        return self.kind.module

    def directions (self):
        out = {}
        for name in self.kind.inputs:
            out[name] = 'in'
        for name in self.kind.outputs:
            out[name] = 'out'
        return out


def blackbox (module, inputs = None, outputs = None, params = None,
              source = None, inouts = None):
    """Declare something the fitter has and isomorph does not.

    inouts exists only to be refused with a reason. A vendor part
    often has one - an IO buffer, a memory data bus - and without the
    argument the error would be that a port is missing, which reads
    like a mistake in the declaration rather than the limit it is.
    """
    if not isinstance(module, str) or not module.isidentifier():
        raise IsomorphError(
            f'blackbox({module!r}): the first argument is the module '
            'name as the fitter knows it.')
    return BlackboxType(module, inputs, outputs, params, source, inouts)
